kind: pipeline
name: default

steps:
- name: lint
  image: hadolint/hadolint:v2.8.0-debian
  commands:
  - hadolint - < Dockerfile

- name: publish
  image: plugins/docker:20:10
  settings:
    username: mhetzel 
    password: 
      from_secret: DOCKER_PASSWORD
    registry: registry.hub.docker.com
    repo: registry.hub.docker.com/mhetzel/fantomopera
    tags: 
    - latest
    - ${DRONE_TAG}
  when:
    event:
    - tag

trigger:
  branch:
  - main
