kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username: mhetzel 
    password: 
      from_secret: DOCKER_PASSWORD
    registry: registry.hub.docker.com
    repo: registry.hub.docker.com/mhetzel/fantomopera
    tags: 
    - latest
    - ${DRONE_TAG}
  when:
    event:
    - tag
