kind: pipeline
type: docker
name: default


publish:
  image: plugins/docker
  username: mhetzel 
  password: 
    from_secret: DOCKER_PASSWORD
  registry: registry.hub.docker.com
  repo: registry.hub.docker.com/mhetzel/fantomopera
  tag: latest
